version: "3.7"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - 3306:3306
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sys
      MYSQL_USER: user
      MYSQL_PASSWORD: password